import type {
  ImplementationRange,
  SigilDiagnosticSeverity,
  SourceRange,
} from "./language.ts";
export type { SigilDiagnosticSeverity, SourceRange } from "./language.ts";

export type SigilDiagnosticCode =
  | "SIGIL_PARSE_STRUCTURE"
  | "SIGIL_UNKNOWN_SECTION"
  | "SIGIL_MISSING_GOAL"
  | "SIGIL_MISSING_INTERFACE"
  | "SIGIL_INVALID_ENCODING"
  | "SIGIL_INVALID_CHARACTER"
  | "SIGIL_UNCLOSED_BLOCK"
  | "SIGIL_DUPLICATE_SECTION"
  | "SIGIL_EMPTY_TAG_GROUP"
  | "SIGIL_NESTED_TAG_GROUP"
  | "SIGIL_INCOMPLETE_TAG"
  | "SIGIL_INVALID_TAG_NAME"
  | "SIGIL_DUPLICATE_TAG_DEFINITION"
  | "SIGIL_DUPLICATE_TAG_IMPORT"
  | "SIGIL_TAG_NAME_COLLISION"
  | "SIGIL_UNRESOLVED_IMPORTED_TAG"
  | "SIGIL_UNUSED_TAG_IMPORT"
  | "SIGIL_LINK_TARGET_UNAVAILABLE"
  | "SIGIL_INTERPRETATION_UNRESOLVED"
  | "SIGIL_SEMANTIC_CONFLICT"
  | "SIGIL_LAYOUT_DEPENDENT_PROSE"
  | "SIGIL_DETACHED_LITERAL_BLOCK"
  | "SIGIL_LITERAL_WITHOUT_INTRODUCTION"
  | "SIGIL_UNCLOSED_LITERAL_BLOCK"
  | "SIGIL_INVALID_LITERAL_TYPE"
  | "SIGIL_LINE_TOO_LONG"
  | "SIGIL_UNFORMATTABLE_LINE"
  | "SIGIL_FORMAT_CONTEXT_UNAVAILABLE"
  | "SIGIL_UNRESOLVED_IMPORT_PATH"
  | "SIGIL_UNRESOLVED_IMPORTED_COMPONENT"
  | "SIGIL_DUPLICATE_COMPONENT"
  | "SIGIL_CONFIG_NOT_FOUND"
  | "SIGIL_CONFIG_PARSE"
  | "SIGIL_CONFIG_INVALID"
  | "SIGIL_UNSUPPORTED_VERSION"
  | "SIGIL_NESTED_CONFIG"
  | "SIGIL_CONFIG_EXISTS"
  | "SIGIL_CONFIG_UNKNOWN_PROFILE"
  | "SIGIL_CONFIG_UNKNOWN_EVALUATOR"
  | "SIGIL_CONFIG_UNKNOWN_PROVIDER"
  | "SIGIL_CONFIG_STAGE_CONFLICT"
  | "SIGIL_CONFIG_EVALUATOR_PROVIDER_CONFLICT"
  | "SIGIL_GLOSSARY_PARSE"
  | "SIGIL_GLOSSARY_INVALID"
  | "SIGIL_GLOSSARY_CONTEXT_OVERLAP"
  | "SIGIL_GLOSSARY_TERM_COLLISION"
  | "SIGIL_IMPLEMENTATION_SOURCE_DISCOVERY"
  | "SIGIL_IMPLEMENTATION_ANNOTATION"
  | "SIGIL_RETRIEVAL_TARGET_PATH_INVALID"
  | "SIGIL_RETRIEVAL_COMPONENT_NOT_FOUND"
  | "SIGIL_RETRIEVAL_COMPONENT_IDENTITY_MISMATCH"
  | "SIGIL_RETRIEVAL_FILE_NOT_FOUND"
  | "SIGIL_RETRIEVAL_FILE_EMPTY"
  | "SIGIL_RETRIEVAL_IMPLEMENTATION_DISCOVERY_UNAVAILABLE"
  | "SIGIL_RETRIEVAL_IDENTITY_COLLISION"
  | "SIGIL_RETRIEVAL_EVIDENCE_SNAPSHOT_MISMATCH"
  | "SIGIL_BOUNDARY_SEED_PATH_INVALID"
  | "SIGIL_BOUNDARY_SEED_NOT_FOUND"
  | "SIGIL_BOUNDARY_EXACT_TARGET_UNSUPPORTED";

export type DiagnosticStage =
  | "parsing"
  | "structure"
  | "workspace"
  | "resolution"
  | "interpretation"
  | "host";

export interface DiagnosticLocation {
  readonly filePath?: string;
  readonly range?: SourceRange;
  readonly sourceDigest?: string;
  readonly implementationRange?: ImplementationRange;
}

export interface RelatedDiagnosticLocation extends DiagnosticLocation {
  readonly message?: string;
}

export interface SigilDiagnostic extends DiagnosticLocation {
  readonly code: SigilDiagnosticCode;
  readonly stage: DiagnosticStage;
  readonly severity: SigilDiagnosticSeverity;
  readonly message: string;
  readonly related: readonly RelatedDiagnosticLocation[];
}
