import type { SigilDiagnosticSeverity, SourceRange } from "./language.ts";
export type { SigilDiagnosticSeverity, SourceRange } from "./language.ts";

export type SigilDiagnosticCode =
  | "SIGIL_PARSE_STRUCTURE"
  | "SIGIL_UNKNOWN_SECTION"
  | "SIGIL_SECTION_NOT_ALLOWED"
  | "SIGIL_MISSING_GOAL"
  | "SIGIL_MISSING_INTERFACE"
  | "SIGIL_MODULE_WITHOUT_COMPONENT"
  | "SIGIL_MISSING_CONCEPT_IDENTIFIER"
  | "SIGIL_INVALID_CONCEPT_IDENTIFIER"
  | "SIGIL_EMPTY_CONCEPT_BLOCK"
  | "SIGIL_NESTED_CONCEPT_BLOCK"
  | "SIGIL_AMBIGUOUS_CONCEPT_IDENTIFIER"
  | "SIGIL_CONCEPT_IDENTIFIER_STYLE"
  | "SIGIL_DETACHED_LITERAL_BLOCK"
  | "SIGIL_LITERAL_WITHOUT_INTRODUCTION"
  | "SIGIL_UNCLOSED_LITERAL_BLOCK"
  | "SIGIL_INVALID_LITERAL_TYPE"
  | "SIGIL_LINE_TOO_LONG"
  | "SIGIL_UNFORMATTABLE_LINE"
  | "SIGIL_UNRESOLVED_IMPORT_PATH"
  | "SIGIL_UNRESOLVED_IMPORTED_COMPONENT"
  | "SIGIL_UNUSED_IMPORT"
  | "SIGIL_EXPAND_WITHOUT_COMPONENT"
  | "SIGIL_DUPLICATE_COMPONENT"
  | "SIGIL_IMPORT_CYCLE"
  | "SIGIL_CONFIG_NOT_FOUND"
  | "SIGIL_CONFIG_PARSE"
  | "SIGIL_CONFIG_INVALID"
  | "SIGIL_UNSUPPORTED_VERSION"
  | "SIGIL_NESTED_CONFIG"
  | "SIGIL_CONFIG_EXISTS"
  | "SIGIL_CONFIG_UNKNOWN_PROFILE"
  | "SIGIL_CONFIG_UNKNOWN_EVALUATOR"
  | "SIGIL_CONFIG_UNKNOWN_PROVIDER"
  | "SIGIL_CONFIG_STAGE_CONFLICT"
  | "SIGIL_CONFIG_EVALUATOR_PROVIDER_CONFLICT"
  | "SIGIL_GLOSSARY_PARSE"
  | "SIGIL_GLOSSARY_INVALID"
  | "SIGIL_GLOSSARY_CONTEXT_OVERLAP"
  | "SIGIL_GLOSSARY_TERM_COLLISION"
  | "SIGIL_IMPLEMENTATION_SOURCE_DISCOVERY"
  | "SIGIL_RETRIEVAL_TARGET_PATH_INVALID"
  | "SIGIL_RETRIEVAL_COMPONENT_NOT_FOUND"
  | "SIGIL_RETRIEVAL_COMPONENT_IDENTITY_MISMATCH"
  | "SIGIL_RETRIEVAL_FILE_NOT_FOUND"
  | "SIGIL_RETRIEVAL_FILE_EMPTY"
  | "SIGIL_RETRIEVAL_IMPLEMENTATION_DISCOVERY_UNAVAILABLE"
  | "SIGIL_RETRIEVAL_IDENTITY_COLLISION"
  | "SIGIL_RETRIEVAL_EVIDENCE_SNAPSHOT_MISMATCH"
  | "SIGIL_BOUNDARY_SEED_PATH_INVALID"
  | "SIGIL_BOUNDARY_SEED_NOT_FOUND"
  | "SIGIL_BOUNDARY_EXACT_TARGET_UNSUPPORTED";

export interface SigilDiagnostic {
  readonly code: SigilDiagnosticCode;
  readonly severity: SigilDiagnosticSeverity;
  readonly message: string;
  readonly filePath?: string;
  readonly range?: SourceRange;
}
