/** Generate the pinned Sigil word-character table from a supplied UnicodeData file. */
const expected =
  "2fc713e6a31a87c4850a37fe2caffa4218180fadb5de86b43a143ddb4581fb86";
const bytes = await Deno.readFile(Deno.args[0]);
const digest = [...new Uint8Array(await crypto.subtle.digest("SHA-256", bytes))]
  .map((n) => n.toString(16).padStart(2, "0")).join("");
if (digest !== expected) {
  throw new Error("Expected Unicode 15.1.0 UnicodeData.txt");
}
const ranges: [number, number][] = [];
let first: number | undefined;
for (const row of new TextDecoder().decode(bytes).split("\n")) {
  if (!row) continue;
  const [hex, name, category] = row.split(";");
  const code = parseInt(hex, 16);
  if (name.endsWith(", First>")) {
    first = code;
    continue;
  }
  const start = name.endsWith(", Last>") ? first! : code;
  if (
    /^[LMN]/.test(category) || category === "Pc" || code === 0x200c ||
    code === 0x200d
  ) {
    const previous = ranges.at(-1);
    if (previous && previous[1] + 1 === start) previous[1] = code;
    else ranges.push([start, code]);
  }
}
const output =
  `// Generated by packages/core/scripts/generate-word-characters.ts.\n` +
  `// Unicode 15.1.0 L/M/N/Pc plus U+200C/U+200D. See UNICODE-LICENSE.txt.\n` +
  `// https://www.unicode.org/Public/15.1.0/ucd/UnicodeData.txt\n` +
  `// SHA-256: ${expected}\n` +
  `export const WORD_CHARACTER_RANGES: readonly (readonly [number, number])[] = [\n` +
  ranges.map(([a, b]) => `  [0x${a.toString(16)}, 0x${b.toString(16)}],`).join(
    "\n",
  ) +
  `\n];\n`;
await Deno.writeTextFile(
  new URL("../src/data/word-characters-15.1.ts", import.meta.url),
  output,
);
