/**
 * Generate the Rust language tables from the sources both parsers share.
 *
 * Usage: deno run --allow-read --allow-write scripts/generate-language-tables.ts <entities.json>
 *
 * The word-character ranges come from the pinned TypeScript table, so the two
 * parsers read one set of ranges. The entity table comes from the WHATWG
 * `entities.json` (pinned by digest), the same data `entities/decode` ships.
 */
import { WORD_CHARACTER_RANGES } from "../packages/core/src/data/word-characters-15.1.ts";

const ENTITIES_SHA256 =
  "d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6";
const outputDir = new URL(
  "../packages/sigilc/src/language/data/",
  import.meta.url,
);

const entitiesPath = Deno.args[0];
if (!entitiesPath) {
  throw new Error("Pass the path to the WHATWG entities.json");
}
const bytes = await Deno.readFile(entitiesPath);
const digest = [...new Uint8Array(await crypto.subtle.digest("SHA-256", bytes))]
  .map((n) => n.toString(16).padStart(2, "0")).join("");
if (digest !== ENTITIES_SHA256) {
  throw new Error(`Unexpected entities.json digest ${digest}`);
}

const hex = (n: number) => `0x${n.toString(16)}`;
const words = `// Generated by scripts/generate-language-tables.ts. Do not edit.
// Unicode 15.1.0 L/M/N/Pc plus U+200C/U+200D, from packages/core/src/data/word-characters-15.1.ts.
pub const WORD_CHARACTER_RANGES: &[(u32, u32)] = &[
${
  WORD_CHARACTER_RANGES.map(([a, b]) => `    (${hex(a)}, ${hex(b)}),`).join(
    "\n",
  )
}
];
`;

const entities = JSON.parse(new TextDecoder().decode(bytes)) as Record<
  string,
  { characters: string }
>;
const names = Object.keys(entities).sort();
const rustString = (text: string) =>
  `"${
    [...text].map((c) => `\\u{${c.codePointAt(0)!.toString(16)}}`).join("")
  }"`;
const html = `// Generated by scripts/generate-language-tables.ts. Do not edit.
// WHATWG HTML named character references (entities.json, SHA-256 ${ENTITIES_SHA256}).
// Names are stored without the leading '&', sorted for binary search; legacy names without ';' are included.
pub const HTML_ENTITIES: &[(&str, &str)] = &[
${
  names.map((n) =>
    `    ("${n.slice(1)}", ${rustString(entities[n].characters)}),`
  )
    .join("\n")
}
];
`;

await Deno.mkdir(outputDir, { recursive: true });
await Deno.writeTextFile(new URL("word_characters.rs", outputDir), words);
await Deno.writeTextFile(new URL("html_entities.rs", outputDir), html);
